version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
    networks:
      - dcicflix-network

networks:
  dcicflix-network:
    driver: bridge

volumes:
  mongo-data: